version: '3.1'

services:

  backend:
    depends_on:
     - mongodb
    image: application-backend
    networks:
     - cicdapp
    ports:
     - 3000:3000
    container_name: app-backend
    restart: unless-stopped
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    volumes:
     - data:/etc/mongo
    networks:
     - cicdapp

networks:
  cicdapp:
volumes:
  data: