---
- name: Deploy Docker Compose
  hosts: webserver
  gather_facts: yes
  become: true

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    compose_file_path: /home/ubuntu/backend/docker-compose.yml
    github_repo: github.com/CICDassignment/backend.git
    github_credentials_id: mumernaeem1123
    git_access_token: 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
    repo_url: "{{ github_credentials_id }}:{{ git_access_token }}@{{ github_repo }}"

  tasks:
    - name: Check if Docker is already installed
      command: docker --version
      register: docker_version
      ignore_errors: true

    - name: apt update
      apt:
        update_cache: yes

    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present
      when: docker_version.rc != 0
    
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      become: true

    - name: Create Project directory
      file:
        path: /home/ubuntu/backend
        state: directory
        mode: '0755'

    - name: Check if Docker Compose file exists
      stat:
        path: "{{ compose_file_path }}"
      register: compose_file_stat

    - name: Clone private GitHub repository
      git:
        repo: "https://{{ repo_url }}"
        dest: /home/ubuntu/backend
        version: main
        clone: yes
        depth: 1
        force: yes
        accept_hostkey: yes
      become: true

    - name: Build Docker image
      docker_image:
        name: application-backend
        path: /home/ubuntu/backend
        dockerfile: Dockerfile
        force: yes

    - name: Ensure the Dockerfile exists
      stat:
        path: /home/ubuntu/backend/Dockerfile
      register: dockerfile_exists

    - name: Run Docker Compose if the file exists
      docker_compose:
        project_src: /home/ubuntu/backend
        files:
          - "{{ compose_file_path }}"
        build: yes
      when: compose_file_stat.stat.exists
      become: true